version: '3.8'
services:
  server:
    image: compose-lenotes-server:prod
    build:
      context: ./server
      dockerfile: ./src/Web/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - CLIENT_URL=http://localhost:8080
      - PORT=5000

  client:
    image: compose-lenotes-client:prod
    build:
      context: ./client
      dockerfile: ./Dockerfile
      args:
        - GROUPS_ROOT_URL
        - NOTES_ROOT_URL
    ports:
      - '8080:8080'
